### ISSUE TITLE
Crawlers stops

### ISSUE THREAD

**Issue by ghost** [Elders/Multithreading.Scheduler#3]
does the crawler stop automatically once all workers on it stops ?

**Comment by mynkow** [comment]
When you stop the crawler it sends stop signal to all works. It waits for all works in progress to finish and then everything stops.

**Comment by ghost** [comment]
Thanks for your reply . 
I created a simple demo which a for loops 2000 time . but it seems that it restart every time it finishes ? 

demo : 

```
    class Program
    {
        public static WorkPool pool;
        public static List<AtomicInteger> state = new List<AtomicInteger>();
        static void Main(string[] args)
        {
            
            state.Add(new HunterTest.AtomicInteger());
            state.Add(new HunterTest.AtomicInteger());
            state.Add(new HunterTest.AtomicInteger());
            state.Add(new HunterTest.AtomicInteger());
            state.Add(new HunterTest.AtomicInteger());

            string poolName = "This name is assigned to the current Thread.Name";
            int numberOfThreadsAvailableForThePool = state.Count;

            pool = new WorkPool(poolName, numberOfThreadsAvailableForThePool);
            for (int i = 0; i < numberOfThreadsAvailableForThePool; i++)
            {
                var work = new IncrementByOne(state[i]);
                work.Finished += Work_Finished;
                pool.AddWork(work);
            }
            pool.StartCrawlers();


            Console.ReadLine();
        }

        private static void Work_Finished(object sender, EventArgs e)
        {
            if (state.Where(x => !x.Finished).Count() <= 0)
            {

            }
               
        }
    }

    public class IncrementByOne : IWork
    {
        private readonly AtomicInteger state;

        public event EventHandler Finished;

        public IncrementByOne(AtomicInteger state)
        {
            this.state = state;
        }

        public string Name
        {
            get
            {
                return this.GetType().ToString();
            }
        }

        public DateTime ScheduledStart { get; set; }

        public void Start()
        {
            state.Increment();
            Stop();
            Finished(this, null);
        }

        public void Stop()
        {
            //  Do cleanup here.
        }
    }

    public class AtomicInteger
    {
        private int currentValue = 500;
         
        public bool Finished { get; set; }

        public void Increment()
        {
            if (currentValue == 500)
            {
                for (var i = 0; i < 500; i++)
                {

                }
                Finished = true;
            }
        }
    }
```

**Comment by mynkow** [comment]
This is correct. I was confused at first because you wanted to stop the crawler. For example, when you have this running as a windows service and you want to stop the service the crawler is doing a graceful stop without terminating any work in progress.

The main purpose of the scheduler is long running repeatable tasks. We are using the `Multithreading.Scheduler` to [dequeue messages from a message broker](https://github.com/Elders/Cronus/blob/master/src/Elders.Cronus/Pipeline/ContinuousConsumer.cs). When the work finishes or an error is thrown we reschedule the work to be executed at the specified time using `ScheduledStart`. 

I guess you want to schedule a single task which executes once and when finishes it has to exit, correct? Could you please share what is your usecase?

**Comment by ghost** [comment]
Exactly . I have a sweeper which sweep a background work every 60 secondes (this can take longer depends on whether the previous one is finished or not ) . and then on my method Sweep() I'm creating a pool using Multithreading.Scheduler to execute a batch once all the workers on my batch is finished i want to stop the crawler . what i did which i still don't know if its suitable is i created an Event on workers . and subscribed to them before adding them to the pool and when the worker finishes i'm firing the event and i'm letting the database know about a finished worker on the batch which contains for example 5 workers and when the finished workers equals to the total batch workers 5 = 5 i stops the crawlers

**Comment by mynkow** [comment]
Just checking if I got this. You have a BIG task which you want to distribute to several workers but if one fails the entire batch should fail. Ideally you want to be notified when everything finishes successfully.

If this is correct, do you see several workers on several nodes/machines?

**Comment by ghost** [comment]
Not exactly on my database i have a batch of tasks (e.g 5 tasks ) when the sweep() hits i'm splitting those 5 tasks to workers and execute them on a pool . i already know that i have 5 tasks and i have an Onfinished Event on each of those instances . once i collect 5 fired events (Onifinished) i would ideally know that my batch is finished . and on the 5's event hit i m calling pool.Stop() which will stops all the workers

**Comment by mynkow** [comment]
Seems fine to me. Just make sure that you unsubscribe from the event `Finished`. 

Also, what you could do once the work is done is to reschedule it for after 5 years so it is not executed again. For example;

```
public void Start()
        {
            state.Increment();
            //Stop();
            Finished(this, null);
           ScheduledStart = DateTime.UtcNow.AddYears(5);
        }
```

**Comment by ghost** [comment]
that's the issue here why when calling Stop(); the process is not stopped ? 
normally when calling the pool.stop(); it should stops all the workers ?

**Comment by mynkow** [comment]
It is an implementation detail. The pool has no idea how to stop the work gracefully. The pool.stop just execute work.stop and it is up to the specific implementation how a work could be force stopped. So i suggest the Start() method from my prev comment above to schedule the work's next run to utc.Addyears(5) on a successful execution and a boolean state tracker from the ContinuousConsumer for implementing stop/cancel

**Comment by ghost** [comment]
My worker basically do an Api call and parse a response and save it on the DB.
once he finishes why the start() method is called once again ? 
the job is stopped automatically without having to use pool.stop() , if so i would rather use it to clean up the threads then stops the actual job
